//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesorios_Instrumento
    {
        public int ID { get; set; }
        public string Id_Instrumento { get; set; }
        public string Instrumento { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string NS { get; set; }
        public string Ubicacion { get; set; }
        public string Magnitud { get; set; }
        public string Uso { get; set; }
        public string Observacion { get; set; }
        public string Id_Accesorio { get; set; }
        public string Estatus_Asignacion { get; set; }
    }
}
