//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estandares
    {
        public int Id { get; set; }
        public string Id_Estandares { get; set; }
        public string Estandar { get; set; }
        public string Uso { get; set; }
        public string Marca { get; set; }
        public string Presentacion { get; set; }
        public string FechaDeFabricacion { get; set; }
        public string FechaDeCaducidad { get; set; }
        public string Ubicacion { get; set; }
        public string Estatus { get; set; }
        public string Inventario { get; set; }
        public string Estatus_Prestamo { get; set; }
        public string NoLote { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> NoLotes_Disponibles { get; set; }
    }
}
