//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrumentos
    {
        public int ID { get; set; }
        public string ID_Instrumentos { get; set; }
        public string INSTRUMENTO { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string N_S_ { get; set; }
        public string UBICACIÓN { get; set; }
        public string OBSERVACIÓN { get; set; }
        public string ESTATUS { get; set; }
        public string ESTATUS_ASIGNACION { get; set; }
        public string MAGNITUD { get; set; }
        public string RANGO { get; set; }
        public string ACCESORIOS { get; set; }
        public string USO { get; set; }
        public string INTERVALO_DE_MEDIA { get; set; }
    }
}
